// <auto-generated />
using FilmesApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmesApi.Migrations
{
    [DbContext(typeof(FilmeDbContext))]
    partial class FilmeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmesApi.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Jane Campion",
                            Duration = 60,
                            Genre = "Suspense",
                            Name = "Blade Runner"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Quentin Tarantino",
                            Duration = 90,
                            Genre = "Documentário",
                            Name = "Trainspotting - Sem Limites"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Sofia Coppola",
                            Duration = 90,
                            Genre = "Romance",
                            Name = "Gênio Indomável"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Petra Costa",
                            Duration = 120,
                            Genre = "Romance",
                            Name = "Titanic"
                        },
                        new
                        {
                            Id = 5,
                            Director = "Sofia Coppola",
                            Duration = 120,
                            Genre = "Desenho",
                            Name = "Aliens, O Resgate"
                        },
                        new
                        {
                            Id = 6,
                            Director = "Kathryn Bigelow",
                            Duration = 60,
                            Genre = "Ficção",
                            Name = "Um Sonho de Liberdade"
                        },
                        new
                        {
                            Id = 7,
                            Director = "Jean-Luc Godard",
                            Duration = 120,
                            Genre = "Policial",
                            Name = "Blade Runner"
                        },
                        new
                        {
                            Id = 8,
                            Director = "Alfred Hitchcock",
                            Duration = 60,
                            Genre = "Romance",
                            Name = "Noivo Neurótico, Noiva Nervosa"
                        },
                        new
                        {
                            Id = 9,
                            Director = "Steven Spielberg",
                            Duration = 90,
                            Genre = "Aventura",
                            Name = "Uma Vida sem Limites"
                        },
                        new
                        {
                            Id = 10,
                            Director = "Stanley Kubrick",
                            Duration = 90,
                            Genre = "Ficção",
                            Name = "Donnie Darko"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
